### PR TITLE
Added Registration form and SearchPatient form functionality to the Home Page

### PR DESCRIPTION
**Pull request by SatyaraoK**

### CODE REVIEW

**Comment by Project-healthme** [comment]
Indrasena Reddy,
Mail to: indrasena_4u@live.com,
Contact: +91 9566012851

**Review by SatyaraoK — COMMENTED** [review]
Guys, Added UI frameset , pls can cehck .

**Comment by SatyaraoK** [comment]
fine. Thanks


*ThanksSatya*

**Pull request merged**
